[package]
name = "dash-palette-util"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "dphu"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
